### ISSUE TITLE
Missing check in PatriciaTreeMap::leq implementation

### ISSUE THREAD

**Issue by arthaud** [facebookincubator/SPARTA#1]
Hello spartans (Salut Arnaud!),

I think there is a bug in the PatriciaTreeMap::leq() implementation.

If both trees are leaves, you should check if the keys are the same before comparing the values:

https://github.com/facebookincubator/SPARTA/blob/b1d453e871941b095e0297b6f8065e1230729309/include/PatriciaTreeMap.h#L500

Best regards

**Comment by arnaudvenet** [comment]
Salut Maxime,

I can see that you still have the knack of finding subtle problems in Abstract Interpretation algorithms 🙂.

I'll go ahead and fix this.

Thanks!

**Comment by arnaudvenet** [comment]
Fixed by commit [0228ec6e9c049d7782f195e3d407dde351255df6](https://github.com/facebookincubator/SPARTA/commit/0228ec6e9c049d7782f195e3d407dde351255df6).
