### ISSUE TITLE
Purely virtual function and CRTP

### ISSUE THREAD

**Issue by tellenbach** [facebookincubator/SPARTA#2]
Hello together,

first of all: Thank you for releasing SPARTA on Github. As someone highly interested in static analysis and abstract interpretation I'm really excited about this. So again: Thank you.

I've got a question regarding your use of CRTP in the definition of `AbstractDomain` and `AbstractValue`. Nevertheless these classes are designed to use CRTP, they contain purely virtual functions. 

Regarding libraries using CRTP you often see a function like this

    Derived& derived() { return *static_cast<Derived*>(this); }

and a const version of that. A purely virtual function `virtual void foo() = 0;` can then be replaced by

    inline void foo() { return derived().foo(); }

A method call to `foo` will then be completely statically dispatched. This would maybe decrease the binary size (since vtables are smaller) and could increase the performance (due to static dispatching). We use this approach at the high performance linear algebra library Eigen and I guess it works quite well.

I see the following downsides:

 1. Code gets more complicated and looks less clean
2. No inbuilt compile-time check if a subclass implements a method (a call to a former purely virtual function will seg. fault at runtime). However, since SPARTA already depends on Boost, we could use [Boost TTI](https://www.boost.org/doc/libs/1_69_0/libs/tti/doc/html/index.html) to add checks in the (still virtual) destructor.
3. No inbuilt `override` (and I have no idea how to mimic one)

I guess performance is crucial if you want a static analysis tool to be widely adopted and therefore want to advertise the changes suggested above.

If you are interested in a pull request addressing the ideas above, I would prepare something. 

Cheers,
David

**Comment by int3** [comment]
Thanks for raising this issue. I think your assessment of the tradeoffs are spot on, but the big question here is how much performance we are trading off here. Intuitively my guess is that the overhead of virtual dispatch is small compared to the cost of executing the method bodies; there's also the possibility that modern C++ compilers can devirtualize them, but we haven't checked. That said, I'm inclined not sacrifice ease-of-use & compile-time correctness unless there are clear numbers demonstrating the performance gain. Performance is important for adoption but so are the other two qualities.

**Comment by arthaud** [comment]
I believe compilers do a good job at optimizing virtual method calls (devirtualizing), especially since the derived classes are marked `final` here.

My 2 cents.
